### ISSUE TITLE
Dollar character in master password not accepted

### ISSUE THREAD

**Issue by sebw** [kbialek/ulauncher-bitwarden#5]
Hi,

If the master password contains a special character `$`, it is not possible to login.

**Comment by kbialek** [comment]
hi @sebw 

Sorry, I could not reproduce this problem.

I created a test account with password `asd$asd$123` and it is working fine. On the other hand, since the extension is using `bw` cli I belive the problem might lie in bw-cli distribution you are using. Especially it might pass the password unquoted and therefore parts of the password are interpretted as shell variables.

For example:
```
>>> echo asd$asd$123 
asd23
```

This can be solved either by quotation
```
>>> echo 'asd$asd$123'
asd$asd$123
```

or by escaping
```
>>> echo asd\$asd\$123 
asd$asd$123
```

Please check if you can login from the command line directly.

**Comment by sebw** [comment]
Hi,

Apologies for the incorrect report/assumption. I will investigate a bit further (including your suggestion) and get back to you.

Cheers

**Comment by pragmaticus** [comment]
Stumbled upon the same problem with an `!` in my master password. Quoting the password or escaping it within the password dialog does not work.
