### ISSUE TITLE
Unable to unlock vault on Fedora KDE

### ISSUE THREAD

**Issue by mplessis** [kbialek/ulauncher-bitwarden#6]
Hello,

i'm on Fedora KDE spin and i'm unable to unlock my vault. Bw cli is correctly installed with snap and recognized by command line and by python, but when i run bw in ulauncher the only option appears is "loading" with the icon of bitwarden search extension. I have set my email address in settings.

Could you help me please ?

(Sorry for my poor english)

Marc

**Comment by kbialek** [comment]
hi Marc! Exit ulauncher and start it from the CLI. Try to use the extension and then inspect the output in the CLI. Maybe that will give you a hint about what the problem is.

**Comment by mplessis** [comment]
Hi kbialek,

i'm trying your suggestion but it's produce the same result. I'm an error which is "Failed to load appmenu-gtk-module" but i doubt this is the reason of my problem.

Is there a log file of extension or ulauncher where errors is writing (i search that but not found it)

**Comment by kbialek** [comment]
hi! If you are familiar with Python or programming in general, you can try to find the issue within the extension on your own. In order to do it
1. Uninstall the extension from ulauncher
2. Clone this repo
3. Go to the cloned project
4. Install extension using script `dev/install_dev_extension.sh`
5. Open exention code and add as many `print()` as you need
6. Start ulaucher in the CLI and check what does it print

**Comment by mplessis** [comment]
Ok thank you for this solution, i'm a developer and will try this. i'm back here and saying the result

**Comment by mplessis** [comment]
Ok everything works. After investigating on this problem, the reason of this fail is that snap version of bw cli show an error "cgroup v2 not yet fully supported" (i use a Fedora 33), and this error message failing the functions which parse stout and stderr.

I replace bw cli snap version by npm version and now it's ok.

Thank you for the time you get on my problem

Best regards
